worker_processes 1;
events { worker_connections 1024; }

http {
  include       mime.types;
  default_type  application/octet-stream;
  sendfile        on;
  keepalive_timeout  65;

  server {
    listen 80;
    server_name _;

    root /home/ec2-user/frontend;

    # Serve a static JSON file for lista-ingredientes
    location = /lista-ingredientes {
      add_header Content-Type application/json;
      add_header Access-Control-Allow-Origin *;
      add_header Access-Control-Allow-Methods "GET, OPTIONS";
      add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept";
      
      if ($request_method = OPTIONS) {
        return 204;
      }
      
      alias /home/ec2-user/frontend/lista-ingredientes.json;
    }

    # Serve frontend (static files)
    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
