name: CI/CD para EC2 pública e privada

on:
  push:
    branches:
      - master # O branch que acionará o deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      # 2. Configuração do ambiente Node
      - name: FE - Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      # 3. Build da aplicação (Se for uma aplicação que precisa ser construída, ex: React, Angular, Vue)
      - name: FE - Instalar Dependências e Fazer Build
        run: |
             npm install
             npm install axios
             npm run build --if-present 
             # Se sua app não precisar de build, remova esta etapa
        working-directory: ./anjos-bolos-front-end

      # 4. Deploy - Copiar arquivos do build do frontend
      - name: FE - Copiar arquivos de build do frontend
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          # Diretório de destino para os arquivos estáticos do frontend
          TARGET: /home/${{ secrets.REMOTE_USER }}/frontend
          # Argumentos do rsync para cópia recursiva com compressão e exclusão de arquivos antigos
          ARGS: "-rltgoDzvO --delete" 
          # Copia apenas os arquivos compilados do frontend (dist)
          SOURCE: "./anjos-bolos-front-end/dist/"

      # 5. Deploy - Copiar docker-compose.yaml para o servidor
      - name: Copiar docker-compose.yaml
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          # Diretório raiz do usuário onde ficará o compose
          TARGET: /home/${{ secrets.REMOTE_USER }}/
          # Copia apenas o arquivo compose (ajuste o caminho conforme necessário)
          SOURCE: "./compose.yaml"
          # Script para reiniciar o serviço após a cópia
          SCRIPT: |
            # Reinicia o serviço 'api' usando docker compose
            sudo docker compose restart api
            echo "Serviço reiniciado via docker compose"
